# Site settings
title: "On knowledge and Philosophy"
author: "David Horacio Colmenares"
description: "This is a blog about software, some mathematics, and the occasional philosophy. Not necessarily in that order."
keywords: "Software Engineering, Mathematics, Philosophy, Scala, Epistemology, Existentialism, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"
biography: "I am <a href='https://dhcolmenares.net/new-web/'>David Horacio Colmenares</a>, Moorman-Simon Assistant Professor of Spanish and Latin American Studies at the <a href='http://www.fe.up.pt'>Romance Studies department</a>, Boston University and Research Associate at <a href='https://www.inesctec.pt'>INESC TEC</a>. Here you can find my <a href='/assets/thesis.pdf'>PhD Thesis</a>, my <a href='/assets/cv.pdf'>Résumé</a>, and my <a href='/curriculum/publications/'>Publications</a>."
colophon: © 2022, by David H. Colmenares. Design by Hugo Sereno Ferreira.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/''>Creative Commons (BY-NC-SA)</a>.<br>This site is hosted at <a href='https://pages.github.com/''>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a> and <a href='http://getbootstrap.com'>Bootstrap</a>."

baseurl: "/new-web/"
url: "https://hipomenes.github.io"

github_username: hipomenes
instagram_username: hipomenes

google-analytics: UA-69060-5

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

gems:
- jekyll-sitemap
